name: Test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test_x86_x64:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16, 18, 20]
        arch: [x86, x64]
        exclude:
          # Ubuntu does not ship x86 builds.
          - { os: ubuntu-latest, arch: x86 }
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Node ${{ matrix.node }} ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - name: Install
        run: npm install
      - name: Test
        run: npm test

  test_arm:
    strategy:
      matrix:
        os: [macos-14]
        node: [16, 18, 20]
        arch: [arm64]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Node ${{ matrix.node }} ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - name: Install
        run: npm install
      - name: Test
        run: npm test

  test_linux_arm:
    strategy:
      node: [16, 18, 20]
    runs-on: ubuntu-latest
    name: Linux / Node ${{ matrix.node }} arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          build-args:
            NODE_VERSION: ${{ matrix.node }}
          file: linux_arm.dockerfile
          tags: linux_arm:latest
          load: true
          push: false
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run test
        uses: addnab/docker-run-action@v3
        with:
          image: linux_arm:latest
          run: |
            npm install
            npm test
